package bouncetales;

/**
 * Bounce Tales message ID constants.
 * 
 * This class was auto-generated by BounceTools.
 * It is strongly recommended NOT to edit the data within.
 * 
 * Last revision on: 2023-02-04 19:47
 */
public class MessageID {

	public static final short UI_SELECT = 0;
	public static final short UI_LEAVE = 1;
	public static final short UI_BACK = 2;
	public static final short UI_OK = 3;
	public static final short UI_YES = 4;
	public static final short UI_NO = 5;
	public static final short UI_QUIT = 6;
	public static final short UI_NEW_GAME = 7;
	public static final short DIALOG_NEW_GAME = 8;
	public static final short UI_HIGH_SCORES = 9;
	public static final short UI_GUIDE = 10;
	public static final short UI_CONTINUE = 11;
	public static final short EMPTY = 12;
	public static final short GUIDE_TEXT_1 = 13;
	public static final short GUIDE_TEXT_2 = 14;
	public static final short GUIDE_TEXT_3 = 15;
	public static final short GUIDE_TEXT_4 = 16;
	public static final short GUIDE_TEXT_5 = 17;
	public static final short DIALOG_PAUSE_MENU = 18;
	public static final short DIALOG_QUIT_GAME = 19;
	public static final short UI_RESTART_LEVEL = 20;
	public static final short DIALOG_RESTART_LEVEL = 21;
	public static final short UI_CONTINUE_LEVEL = 22;
	public static final short UI_RETURN_LEVEL_SELECT = 23;
	public static final short DIALOG_RETURN_LEVEL_SELECT = 24;
	public static final short GAME_PROGRESS_WILL_BE_LOST = 25;
	public static final short LEVEL_PROGRESS_WILL_BE_LOST = 26;
	public static final short UI_CHAPTERNO_STD = 27;
	public static final short UI_CHAPTERNO_BONUS = 28;
	public static final short NEED_COLLECT_COUNT = 29;
	public static final short BONUS_CHAPTER_UNLOCKED = 30;
	public static final short LEVEL_MISTY_MORNING = 31;
	public static final short LEVEL_UNFRIENDLY_FRIENDS = 32;
	public static final short LEVEL_SEEKING_ANSWERS = 33;
	public static final short LEVEL_SECRET_STALKWAY = 34;
	public static final short LEVEL_BUMPY_CRACKS = 35;
	public static final short LEVEL_INTO_THE_MINES = 36;
	public static final short LEVEL_A_GLOOMY_PATH = 37;
	public static final short LEVEL_RUMBLING_SOUNDS = 38;
	public static final short LEVEL_TUNNEL_OF_TREASURES = 39;
	public static final short LEVEL_TRAPPED_IN_MACHINE = 40;
	public static final short LEVEL_WICKED_CIRCUS = 41;
	public static final short LEVEL_HUNTING_COLOURS = 42;
	public static final short LEVEL_ALMOST_THERE = 43;
	public static final short LEVEL_FANTASTIC_FAIR = 44;
	public static final short LEVEL_FINAL_RIDE = 45;
	public static final short CHAPTER_COMPLETE = 46;
	public static final short DIALOG_GAME_BEATEN = 47;
	public static final short DIALOG_GAME_COMPLETED = 48;
	public static final short ALL_LEVELS_BEATEN = 49;
	public static final short ALL_LEVELS_COMPLETED = 50;
	public static final short TIMER_CHALLENGE = 51;
	public static final short COLLECTION_CHALLENGE = 52;
	public static final short NO_MEDALS_WON = 53;
	public static final short BONUS_CHAPTER_UNLOCKED_DESC = 54;
	public static final short NEW_FORME_UNLOCKED = 55;
	public static final short NEW_HIGH_SCORE = 56;
	public static final short SCORE = 57;
	public static final short SCENARIO_L01E01M01 = 58;
	public static final short SCENARIO_L01E01M02 = 59;
	public static final short SCENARIO_L01E01M03 = 60;
	public static final short SCENARIO_L01E02M01 = 61;
	public static final short SCENARIO_L01E03M01 = 62;
	public static final short SCENARIO_L01E03M02 = 63;
	public static final short SCENARIO_L01E03M03 = 64;
	public static final short SCENARIO_L01E04M01 = 65;
	public static final short SCENARIO_L01E04M02 = 66;
	public static final short SCENARIO_L01E04M03 = 67;
	public static final short SCENARIO_L02E01M01 = 68;
	public static final short SCENARIO_L02E01M02 = 69;
	public static final short SCENARIO_L04E01M01 = 70;
	public static final short SCENARIO_L04E01M02 = 71;
	public static final short SCENARIO_L04E02M01 = 72;
	public static final short SCENARIO_L04E03M01 = 73;
	public static final short SCENARIO_L04E03M02 = 74;
	public static final short SCENARIO_L04E03M03 = 75;
	public static final short SCENARIO_L04E03M04 = 76;
	public static final short SCENARIO_L05_UNUSED = 77;
	public static final short SCENARIO_L08E01M01 = 78;
	public static final short SCENARIO_L08E01M02 = 79;
	public static final short SCENARIO_L08E01M03 = 80;
	public static final short SCENARIO_L08E02M01 = 81;
	public static final short SCENARIO_L11_UNUSED = 82;
	public static final short SCENARIO_L12E01M01 = 83;
	public static final short SCENARIO_L12E01M02 = 84;
	public static final short SCENARIO_L12E02M01 = 85;
	public static final short SCENARIO_L12E02M02 = 86;
	public static final short SCENARIO_L12E02M03 = 87;
	public static final short MM_SS = 88;
	public static final short GAME_TITLE = 89;
	public static final short IS_TEXT_RIGHT_TO_LEFT_RESERVED = 90;
	public static final short UI_MORE_GAMES = -1;

	public static final short[] ALL_MESSAGES_SORTED = new short[]{
		UI_SELECT,
		UI_LEAVE,
		UI_BACK,
		UI_OK,
		UI_YES,
		UI_NO,
		UI_QUIT,
		UI_NEW_GAME,
		DIALOG_NEW_GAME,
		UI_HIGH_SCORES,
		UI_GUIDE,
		UI_CONTINUE,
		EMPTY,
		GUIDE_TEXT_1,
		GUIDE_TEXT_2,
		GUIDE_TEXT_3,
		GUIDE_TEXT_4,
		GUIDE_TEXT_5,
		DIALOG_PAUSE_MENU,
		DIALOG_QUIT_GAME,
		UI_RESTART_LEVEL,
		DIALOG_RESTART_LEVEL,
		UI_CONTINUE_LEVEL,
		UI_RETURN_LEVEL_SELECT,
		DIALOG_RETURN_LEVEL_SELECT,
		GAME_PROGRESS_WILL_BE_LOST,
		LEVEL_PROGRESS_WILL_BE_LOST,
		UI_CHAPTERNO_STD,
		UI_CHAPTERNO_BONUS,
		NEED_COLLECT_COUNT,
		BONUS_CHAPTER_UNLOCKED,
		LEVEL_MISTY_MORNING,
		LEVEL_UNFRIENDLY_FRIENDS,
		LEVEL_SEEKING_ANSWERS,
		LEVEL_SECRET_STALKWAY,
		LEVEL_BUMPY_CRACKS,
		LEVEL_INTO_THE_MINES,
		LEVEL_A_GLOOMY_PATH,
		LEVEL_RUMBLING_SOUNDS,
		LEVEL_TUNNEL_OF_TREASURES,
		LEVEL_TRAPPED_IN_MACHINE,
		LEVEL_WICKED_CIRCUS,
		LEVEL_HUNTING_COLOURS,
		LEVEL_ALMOST_THERE,
		LEVEL_FANTASTIC_FAIR,
		LEVEL_FINAL_RIDE,
		CHAPTER_COMPLETE,
		DIALOG_GAME_BEATEN,
		DIALOG_GAME_COMPLETED,
		ALL_LEVELS_BEATEN,
		ALL_LEVELS_COMPLETED,
		TIMER_CHALLENGE,
		COLLECTION_CHALLENGE,
		NO_MEDALS_WON,
		BONUS_CHAPTER_UNLOCKED_DESC,
		NEW_FORME_UNLOCKED,
		NEW_HIGH_SCORE,
		SCORE,
		SCENARIO_L01E01M01,
		SCENARIO_L01E01M02,
		SCENARIO_L01E01M03,
		SCENARIO_L01E02M01,
		SCENARIO_L01E03M01,
		SCENARIO_L01E03M02,
		SCENARIO_L01E03M03,
		SCENARIO_L01E04M01,
		SCENARIO_L01E04M02,
		SCENARIO_L01E04M03,
		SCENARIO_L02E01M01,
		SCENARIO_L02E01M02,
		SCENARIO_L04E01M01,
		SCENARIO_L04E01M02,
		SCENARIO_L04E02M01,
		SCENARIO_L04E03M01,
		SCENARIO_L04E03M02,
		SCENARIO_L04E03M03,
		SCENARIO_L04E03M04,
		SCENARIO_L05_UNUSED,
		SCENARIO_L08E01M01,
		SCENARIO_L08E01M02,
		SCENARIO_L08E01M03,
		SCENARIO_L08E02M01,
		SCENARIO_L11_UNUSED,
		SCENARIO_L12E01M01,
		SCENARIO_L12E01M02,
		SCENARIO_L12E02M01,
		SCENARIO_L12E02M02,
		SCENARIO_L12E02M03,
		MM_SS,
		GAME_TITLE,
		IS_TEXT_RIGHT_TO_LEFT_RESERVED,
		UI_MORE_GAMES
	};
}
