package bouncetools.message;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import xstandard.fs.FSFile;
import xstandard.io.util.IndentedPrintStream;
import xstandard.text.FormattingUtils;

public class MessageIncludeGenerator {

	public static void generate(FSFile dest, String packageName, Map<String, Short> messageIDMap) throws IOException {
		dest.getParent().mkdirs();
		IndentedPrintStream out = new IndentedPrintStream(dest.getNativeOutputStream());

		if (packageName != null && !packageName.isEmpty()) {
			out.println("package " + packageName + ";");
		}
		out.println();
		out.println("/**");
		out.println(" * Bounce Tales message ID constants.");
		out.println(" * ");
		out.println(" * This class was auto-generated by BounceTools.");
		out.println(" * It is strongly recommended NOT to edit the data within.");
		out.println(" * ");
		out.println(" * Last revision on: " + FormattingUtils.getCommonFormattedDate());
		out.println(" */");
		out.println("public class " + dest.getNameWithoutExtension() + " {");
		out.println();
		out.incrementIndentLevel();

		for (Map.Entry<String, Short> e : messageIDMap.entrySet()) {
			out.println("public static final short " + FormattingUtils.getEnumlyString(e.getKey()) + " = " + e.getValue() + ";");
		}

		out.println();
		out.println("public static final short[] ALL_MESSAGES_SORTED = new short[]{");
		out.incrementIndentLevel();
		int index = 0;
		int count = messageIDMap.size() - 1;
		for (Map.Entry<String, Short> e : messageIDMap.entrySet()) {
			out.println(e.getKey() + (index < count ? "," : ""));
			index++;
		}
		out.decrementIndentLevel();
		out.println("};");

		out.decrementIndentLevel();
		out.println("}");

		out.close();
	}
}
